(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-javadoc-gen-destination-directory "./doc")
 '(jde-run-working-directory "$HOME/Desktop/hexbase")
 '(jde-run-option-classpath (quote ("$HOME/Desktop/Dropbox/Sris and Cliff/H2O/classes" "./lib/sigar/sigar.jar")))
 '(jde-run-option-debug nil)
 '(jde-compile-option-directory "$HOME/Desktop/Dropbox/Sris and Cliff/H2O/classes")
 '(jde-run-option-application-args (quote ("-name" "Cliff")))
 '(jde-debugger (quote ("JDEbug")))
 '(jde-compile-option-source (quote ("1.6")))
 '(jde-compile-option-classpath (quote ("$HOME/Desktop/Dropbox/Sris and Cliff/H2O/classes" "./lib/sigar/sigar.jar" "./lib/hadoop/1.0.0/hadoop-core-1.0.0.jar")))
 '(jde-db-option-classpath (quote ("$HOME/Desktop/Dropbox/Sris and Cliff/H2O/classes")))
 '(jde-run-option-enable-assertions "Everywhere")
 '(jde-compile-option-sourcepath (quote ("./src")))
 '(jde-sourcepath (quote ("./src")))
 '(jde-run-option-hotspot-type (quote server))
 '(jde-compile-option-target (quote ("1.6")))
 '(jde-run-option-heap-size (quote ((512 . "megabytes") (1024 . "megabytes"))))
 '(jde-run-application-class "init.init")
 '(jde-compile-option-debug (quote ("all" (t t t)))))
